version: "3.9"
services:
  postgresql:
    image: postgres:12
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/app
      - ./data:/var/lib/postgresql/data
    network_mode: host
    stdin_open: true 
    tty: true
